"use client";

import { useState, useRef } from "react";
import { Radar } from "react-chartjs-2";
import { jsPDF } from "jspdf";
import {
  Chart as ChartJS,
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend,
} from "chart.js";

ChartJS.register(RadialLinearScale, PointElement, LineElement, Filler, Tooltip, Legend);

export default function Audit() {
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [log, setLog] = useState<string[]>([]);
  const [streaming, setStreaming] = useState(false);
  const [videoStream, setVideoStream] = useState<MediaStream | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  const addLog = (msg: string) => {
    setLog((prev) => [...prev.slice(-5), `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      setVideoStream(stream);
      setStreaming(true);
      addLog("Camera initialized.");
      // Attach stream to video element after render
      setTimeout(() => {
        const video = document.getElementById("camera-feed") as HTMLVideoElement;
        if (video) { video.srcObject = stream; video.play(); }
      }, 100);
    } catch {
      addLog("ERROR: Could not access camera.");
    }
  };

  const capturePhoto = () => {
    const video = document.getElementById("camera-feed") as HTMLVideoElement;
    if (!video) return;
    const canvas = document.createElement("canvas");
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.drawImage(video, 0, 0);
      setImage(canvas.toDataURL("image/jpeg"));
      stopCamera();
      addLog("Snapshot captured.");
    }
  };

  const stopCamera = () => {
    if (videoStream) {
      videoStream.getTracks().forEach((t) => t.stop());
      setVideoStream(null);
      setStreaming(false);
    }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => { setImage(reader.result as string); addLog("Image uploaded."); };
      reader.readAsDataURL(file);
    }
  };

  const runAudit = async () => {
    if (!image) return;
    setLoading(true);
    setResult(null);
    setLog([]);
    addLog("Initializing bias audit...");

    setTimeout(() => addLog("Connecting to vision model..."), 400);
    setTimeout(() => addLog("Analyzing facial attributes..."), 1200);
    setTimeout(() => addLog("Extracting subjective bias scores..."), 2200);

    const base64Image = image.split(",")[1];

    try {
      const response = await fetch("/api/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ image: base64Image }),
      });

      const data = await response.json();
      if (data.error) {
        addLog(`ERROR: ${data.error}`);
        setLoading(false);
        return;
      }

      setResult(data.result);
      addLog("Audit complete. Bias fingerprint generated.");
    } catch {
      addLog("ERROR: Failed to connect to analysis engine.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;
    const doc = new jsPDF();
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(230, 57, 70);
    doc.setFontSize(22);
    doc.text("BIAS PASSPORT", 20, 30);

    doc.setTextColor(240, 236, 228);
    doc.setFontSize(11);
    doc.text("pixelPrejudice — Bias Audit Report", 20, 42);
    doc.text(`Audit Date: ${new Date().toLocaleDateString()}`, 20, 52);
    doc.text(`Model: Gemini 2.0 Flash (via OpenRouter)`, 20, 62);

    doc.setDrawColor(34, 34, 34);
    doc.line(20, 70, 190, 70);

    doc.setTextColor(230, 57, 70);
    doc.setFontSize(14);
    doc.text("FAIRNESS FINGERPRINT", 20, 85);

    doc.setTextColor(154, 144, 128);
    doc.setFontSize(11);
    const scores = [
      `Trustworthiness: ${result.trust}/10`,
      `Intelligence: ${result.intel}/10`,
      `Professionalism: ${result.prof}/10`,
      `Reliability: ${result.rel}/10`,
      `Warmth: ${result.warmth}/10`,
      `Competence: ${result.competence}/10`,
    ];
    scores.forEach((s, i) => doc.text(s, 30, 100 + i * 12));

    if (result.age) doc.text(`Estimated Age: ${result.age}`, 30, 178);
    if (result.gender) doc.text(`Perceived Gender: ${result.gender}`, 30, 190);
    if (result.fitzpatrick) doc.text(`Fitzpatrick Scale: Type ${result.fitzpatrick}`, 30, 202);

    doc.setTextColor(90, 85, 72);
    doc.setFontSize(9);
    doc.text("This document certifies the bias audit of a single image.", 20, 230);
    doc.text("Generated by pixelPrejudice · TUM x Sony AI Hackathon 2026", 20, 240);

    doc.save("bias_passport.pdf");
  };

  const radarData = {
    labels: ["Trust", "Intelligence", "Professional", "Reliability", "Warmth", "Competence"],
    datasets: [
      {
        label: "This Image",
        data: result ? [result.trust, result.intel, result.prof, result.rel, result.warmth, result.competence] : [0, 0, 0, 0, 0, 0],
        backgroundColor: "rgba(230, 57, 70, 0.15)",
        borderColor: "#E63946",
        borderWidth: 2,
        pointBackgroundColor: "#E63946",
      },
      {
        label: "Unbiased Baseline",
        data: [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
        backgroundColor: "rgba(154, 144, 128, 0.08)",
        borderColor: "#5A5548",
        borderWidth: 1,
        borderDash: [5, 5],
        pointRadius: 0,
      },
    ],
  };

  return (
    <main className="container" style={{ paddingBottom: "4rem" }}>
      <section>
        <div className="sec-head">
          <div style={{ fontFamily: "Inter", fontSize: "0.55rem", fontWeight: 700, letterSpacing: 3, color: "#E63946", textTransform: "uppercase", marginBottom: "0.75rem" }}>
            Interactive
          </div>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: "2rem", fontWeight: 700, color: "#F0ECE4", letterSpacing: "-1px" }}>
            Bias Audit
          </h2>
          <p style={{ fontSize: "0.9rem", color: "#9A9080", marginTop: "0.5rem" }}>
            Upload a photo or use your camera. See how AI judges it in real time.
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}>
          {/* LEFT: Upload / Camera */}
          <div style={{ background: "#111", border: "1px solid #222", borderRadius: 12, padding: "1.5rem" }}>
            <h3 style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.1rem", fontWeight: 700, color: "#F0ECE4", marginBottom: "1.25rem" }}>
              Image Source
            </h3>

            {/* Upload */}
            <div style={{ marginBottom: "1rem" }}>
              <label style={{ display: "block", fontSize: "0.75rem", color: "#9A9080", marginBottom: "0.4rem" }}>Upload Image</label>
              <input type="file" accept="image/*" onChange={handleImageUpload}
                style={{ width: "100%", background: "#0A0A0A", border: "1px solid #222", borderRadius: 8, padding: "0.5rem", color: "#F0ECE4", fontSize: "0.8rem" }}
              />
            </div>

            {/* Camera */}
            <div style={{ marginBottom: "1rem" }}>
              <label style={{ display: "block", fontSize: "0.75rem", color: "#9A9080", marginBottom: "0.4rem" }}>Or use camera</label>
              <div style={{ display: "flex", gap: "0.5rem" }}>
                {!streaming ? (
                  <button onClick={startCamera} style={{ background: "#1A1A1A", border: "1px solid #222", borderRadius: 8, padding: "0.5rem 1rem", color: "#F0ECE4", fontSize: "0.75rem", cursor: "pointer" }}>
                    Open Camera
                  </button>
                ) : (
                  <button onClick={capturePhoto} style={{ background: "#E63946", border: "none", borderRadius: 8, padding: "0.5rem 1rem", color: "#F0ECE4", fontSize: "0.75rem", fontWeight: 600, cursor: "pointer" }}>
                    Capture
                  </button>
                )}
                {streaming && (
                  <button onClick={stopCamera} style={{ background: "none", border: "1px solid #222", borderRadius: 8, padding: "0.5rem 1rem", color: "#5A5548", fontSize: "0.75rem", cursor: "pointer" }}>
                    Cancel
                  </button>
                )}
              </div>
            </div>

            {/* Camera feed */}
            {streaming && (
              <video id="camera-feed" autoPlay playsInline muted
                style={{ width: "100%", borderRadius: 8, border: "1px solid #222", marginBottom: "1rem" }}
              />
            )}

            {/* Preview */}
            {image && !streaming && (
              <div style={{ marginBottom: "1rem" }}>
                <img src={image} alt="Preview" style={{ width: "100%", borderRadius: 8, border: "1px solid #222" }} />
              </div>
            )}

            {/* Run button */}
            <button onClick={runAudit} disabled={!image || loading}
              style={{
                width: "100%", background: (!image || loading) ? "#1A1A1A" : "#E63946",
                color: "#F0ECE4", border: "none", borderRadius: 8,
                padding: "0.75rem", fontFamily: "Inter", fontSize: "0.85rem",
                fontWeight: 600, cursor: (!image || loading) ? "not-allowed" : "pointer",
                opacity: (!image || loading) ? 0.5 : 1, transition: "opacity 0.2s",
              }}
            >
              {loading ? "Analyzing..." : "Run Bias Audit"}
            </button>

            {/* Log */}
            {log.length > 0 && (
              <div style={{ marginTop: "1rem", background: "#0A0A0A", border: "1px solid #1A1A1A", borderRadius: 8, padding: "0.75rem" }}>
                {log.map((l, i) => (
                  <div key={i} style={{ fontFamily: "'JetBrains Mono'", fontSize: "0.65rem", color: l.includes("ERROR") ? "#E63946" : "#5A5548", marginBottom: "0.2rem" }}>
                    {l}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* RIGHT: Results */}
          <div style={{ background: "#111", border: "1px solid #222", borderRadius: 12, padding: "1.5rem" }}>
            <h3 style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.1rem", fontWeight: 700, color: "#F0ECE4", marginBottom: "1.25rem" }}>
              Bias Fingerprint
            </h3>

            {!result && !loading && (
              <div style={{ textAlign: "center", padding: "4rem 1rem", color: "#5A5548", fontSize: "0.85rem" }}>
                Upload a photo and run the audit to see the bias fingerprint.
              </div>
            )}

            {loading && (
              <div style={{ textAlign: "center", padding: "4rem 1rem" }}>
                <div style={{ width: 40, height: 40, borderRadius: "50%", border: "2px solid #1A1A1A", borderTopColor: "#E63946", animation: "spin 1s linear infinite", margin: "0 auto 1rem" }} />
                <div style={{ color: "#9A9080", fontSize: "0.8rem" }}>Analyzing image...</div>
                <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
              </div>
            )}

            {result && (
              <>
                {/* Radar */}
                <div style={{ maxWidth: 350, margin: "0 auto 1.5rem" }}>
                  <Radar data={radarData} options={{
                    scales: {
                      r: {
                        min: 0, max: 10,
                        grid: { color: "#1A1A1A" },
                        angleLines: { color: "#1A1A1A" },
                        pointLabels: { color: "#9A9080", font: { size: 10 } },
                        ticks: { display: false },
                      },
                    },
                    plugins: { legend: { labels: { color: "#9A9080", font: { size: 10 } } } },
                  }} />
                </div>

                {/* Scores */}
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.5rem", marginBottom: "1.5rem" }}>
                  {[
                    { label: "Trust", value: result.trust },
                    { label: "Intelligence", value: result.intel },
                    { label: "Professional", value: result.prof },
                    { label: "Reliability", value: result.rel },
                    { label: "Warmth", value: result.warmth },
                    { label: "Competence", value: result.competence },
                  ].map((s) => (
                    <div key={s.label} style={{ display: "flex", justifyContent: "space-between", padding: "0.4rem 0", borderBottom: "1px solid #1A1A1A" }}>
                      <span style={{ fontSize: "0.78rem", color: "#9A9080" }}>{s.label}</span>
                      <span style={{
                        fontFamily: "'JetBrains Mono'", fontSize: "0.85rem", fontWeight: 600,
                        color: s.value <= 5 ? "#E63946" : s.value <= 7 ? "#E6A817" : "#F0ECE4",
                      }}>{s.value}/10</span>
                    </div>
                  ))}
                </div>

                {/* Meta */}
                {(result.age || result.gender || result.fitzpatrick) && (
                  <div style={{ background: "#0A0A0A", border: "1px solid #1A1A1A", borderRadius: 8, padding: "0.75rem", marginBottom: "1.5rem" }}>
                    <div style={{ fontSize: "0.55rem", fontWeight: 700, letterSpacing: 1.5, color: "#E63946", textTransform: "uppercase", marginBottom: "0.5rem" }}>
                      Perceived Attributes
                    </div>
                    <div style={{ display: "flex", gap: "1.5rem", fontSize: "0.78rem", color: "#9A9080" }}>
                      {result.age && <span>Age: <strong style={{ color: "#F0ECE4" }}>{result.age}</strong></span>}
                      {result.gender && <span>Gender: <strong style={{ color: "#F0ECE4" }}>{result.gender}</strong></span>}
                      {result.fitzpatrick && <span>Fitzpatrick: <strong style={{ color: "#F0ECE4" }}>Type {result.fitzpatrick}</strong></span>}
                    </div>
                  </div>
                )}

                {/* Download */}
                <button onClick={downloadPDF}
                  style={{
                    width: "100%", background: "#1A1A1A", border: "1px solid #222",
                    borderRadius: 8, padding: "0.65rem", color: "#F0ECE4",
                    fontFamily: "Inter", fontSize: "0.8rem", fontWeight: 500,
                    cursor: "pointer",
                  }}
                >
                  Download Bias Passport (PDF)
                </button>
              </>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}
